---
title: "Досвід та освіта"
---

## Досвід роботи

| Роки | Посада | Вебсайт |
|------|--------|-------|
| 2024 — по т.ч. | Директор (керівник) Навчально-наукового інституту інформаційних технологій | [ННІ ІТ ХНЕУ ім.&nbsp;С.&nbsp;Кузнеця](https://it.hneu.edu.ua/) |
| 2016 — 2024 | Керівник відділу електронних засобів навчання | [ХНЕУ ім.&nbsp;С.&nbsp;Кузнеця](https://hneu.edu.ua/viddil-tsyfrovoyi-ta-inklyuzyvnoyi-osvity) |
| 2010 — по т.ч. | Доцент кафедри економічної кібернетики і системного аналізу | [Кафедра ЕКСА](https://ek.hneu.edu.ua/) |
| 2008 — 2010 | Старший викладач кафедри економічної кібернетики | ХНЕУ ім. С. Кузнеця |
| 2006 — 2008 | Викладач кафедри економічної кібернетики | ХНЕУ ім. С. Кузнеця |
| 2003 — 2006 | Аспірант кафедри економічної кібернетики | ХНЕУ ім. С. Кузнеця |

---

## Освіта

| Рік | |
|-|----|
| 2007 | Захист кандидатської дисертації «Моделювання цінової політики підприємства в умовах нестаціонарного середовища» у спеціалізованій вченій раді Д 64.055.02 ХНЕУ; диплом кандидата економічних наук за спеціальністю «Математичні методи, моделі та інформаційні технології в економіці» |
| 1998 — 2003 | Харківський державний економічний університет, факультет «Економічної інформатики», спеціальність «Інформаційні управляючі системи», диплом спеціаліста, кваліфікація аналітика комп'ютерних систем |

---

## Підвищення кваліфікації та сертифікати

| Рік | Заклад / Організація | Програма |
|-----|---------------------|----------|
| 2016 | Prometheus | «Як створити масовий відкритий онлайн-курс» |
| 2018 | ХНЕУ | «Розвиток комунікативної компетентності НПП» — [сертифікат](https://drive.google.com/file/d/1Lk2Ns9T2mZgs1AJpfPxM56r9gBVSRxBd/view?usp=drive_link) |
| 2021 | IBM / Coursera | «Fundamentals of Scalable Data Science» — [сертифікат](https://drive.google.com/file/d/1LPLoO4_C0au076ZlZsiOycPFd1XHvohX/view?usp=drive_link) |
| 2021 | IBM / Coursera | «Advanced Machine Learning and Signal Processing» — [сертифікат](https://drive.google.com/file/d/1t7YdOFRZKG8cZdxW-jfmylDUFAP7fSHJ/view?usp=drive_link) |
| 2021 | IBM / Coursera | «Applied AI with DeepLearning» — [сертифікат](https://drive.google.com/file/d/16FOiua7aqPqYwFFv9Kb3RMFyZf3H7Q0x/view?usp=drive_link) |
| 2022 | HVD Hotels (Bulgaria, Varna) | «Development of multimedia technologies for international networks support: European experience» — [сертифікат](https://ek.hneu.edu.ua/wp-content/uploads/2024/02/Roman-YATSENKO_2022_rotated.pdf) |
| 2022 | Genesis (Київ) | «Створення та розвиток IT-продуктів» — [сертифікат](https://drive.google.com/file/d/1pME5BuMcImYMMj-I5bPFgzu7epujv7GW/view?usp=drive_link) |
| 2022 | ХНЕУ | «Академічна доброчесність: практика застосування» — [сертифікат](https://drive.google.com/file/d/1ddZE2kUDbnSSqsdOgoIxStHDqHbVz9jt/view?usp=drive_link) |
| 2022 | LITS | «Основи Web UI розробки 2022» — [сертифікат](https://drive.google.com/file/d/1NDAKqoBfURuGI7YoUA0LSfD-b-suhQ37/view?usp=drive_link) |
| 2025 | ГО "Прогресильні" | «Великий курс про ШІ в освіті» — [сертифікат](https://drive.google.com/file/d/1NDAKqoBfURuGI7YoUA0LSfD-b-suhQ37/view?usp=drive_link) |
| 2025 | ГО "Прогресильні" | «Великий курс про ШІ в освіті» — [сертифікат](https://drive.google.com/file/d/1HSdZIzBGhAX2aJ2x655l5mb9L1meaY8d/view?usp=sharing) |
| 2025 | British Council | Програма професійного розвитку академічних менеджерів «Удосконалення вищої освіти в Україні заради результатів» — [сертифікат](https://drive.google.com/file/d/17xWCLL7GHh3tvc5w5SaqAs_vRu0wV4kN/view?usp=sharing) |
| 2025 | Google for Education | «Академія ШІ для освітніх управлінців від Google» — [сертифікат](https://drive.google.com/file/d/1aVe6QepEbcO_3tO1YDDqO3SnJiMyBZJM/view?usp=sharing) |

---

## Нагороди та відзнаки

| Рік | Відзнака |
|-----|---------|
| 2009 | Переможець IV обласного конкурсу «Найкращий молодий науковець Харківщини» (суспільно-економічні науки) |
| 2017 | Почесна грамота Департаменту освіти Харківської міської ради |
| 2018 | Подяка Міністерства освіти і науки України |
| 2019 | Почесна Грамота Адміністрації Шевченківського району Харківської міської Ради |
| 2021 | Грамота МОН України |
| 2021 | Подяка Харківського міського голови |
| 2023 | Почесна грамота МОН України |
| 2024 | Почесна грамота Харківської міської ради |
| 2025 | Подяка Харківської обласної державної адміністрації |
